version: '3.8'

services:
  cards-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cards_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cards-network

  cards-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cards-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cards-db:5432/cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - cards-network

volumes:
  db-data:

networks:
  cards-network: